# Team: Asgmt1_team25
# Student 1:
## Name: Yi Yang
## Student ID: 1542688
## CCID: yyang13
## Lecture section: B2 Nadi, Sarah
## Lab section: H02

# Student 2:
## Name: Samuel Iwelu
## Student ID: 1574395
## CCID: iwelu
## Lecture section: B2 Nadi, Sarah
## Lab section: H04



demo: encrypt.c
	gcc -Wall -std=c99 encrypt.c -o encrypt

clean:
	-rm -f *.o encrypt core
